stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_NAME: "olooeez/ezcsv"
  DOCKER_IMAGE_TAG: "$CI_COMMIT_TAG"

before_script:
  - apt-get update -qy
  - apt-get install check -y
  tags:
    - gcc

build:
  stage: build
  script:
    - make
  tags:
    - gcc

test:
  stage: test
  script:
    - make check
  tags:
    - gcc

deploy:
  stage: deploy
  only:
    - tags
  script:
    - docker build -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_IMAGE_NAME:latest"
    - docker push "$DOCKER_IMAGE_NAME:latest"
  tags:
    - docker
